name: Report Bug
description: "Report a bug that does not abruptly end a game session or prevent the start of the game."
labels:
- "Status: Triage"
- "Bug: Minor"
body:
- type: markdown
  attributes:
    value: 'Examples of this category include: item duping, item voiding, cannot craft item, behavior and description does not match.

    Please note if you merely want a change, e.g. think something is too OP, you should use the Suggest a Change template instead.'
- type: input
  id: version
  attributes:
    label: Your Pack Version
    description: What version of the pack are you playing? If you're using an ancient version maybe first try updating the pack. We usually fix hundreds of issues per release, so there is a good chance your problem have been fixed already in the latest version. There are also usually Dev releases inbetween Official releases that may not show up on other platforms.
    placeholder: "Example: 2.7.3"
  validations:
    required: true
- type: dropdown
  id: java
  attributes:
    label: Java Version
    description: What Java version are you using? It's worth mentioning that if you play on Java9+ you should try update to latest minor release (e.g. prefer Java 17.0.6 over 17.0.2) of that version.
    options:
    - Java 8
    - Java 9
    - Java 11
    - Java 17
    - Java 19
    - Java 20
    - Java 21
    - Other versions in between
  validations:
    required: true
- type: checkboxes
  id: final
  attributes:
    label: Final Checklist
    description: Please mark them so we can better handle this report
    options:
      - label: "I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report."
        required: true
      - label: "I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole."
        required: false
      - label: "I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole."
        required: false
