name: Auto Tag Issues

on:
  issues:
    types: [opened, edited]

jobs:
  auto_tag_issues:
    runs-on: ubuntu-latest steps:
      - name: Add tag based on template
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const newLabels = [...issue.labels.map(label => label.name)];

            if (issue.body.includes('000-BugReport') && !newLabels.includes('bug')) {
              newLabels.push('bug');
            }
            else if (issue.body.includes('001-RequestFeature') && !newLabels.includes('Feature')) {
              newLabels.push('Feature');
            }

            if (newLabels.length > issue.labels.length) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: newLabels });
            }
