name: Auto Close Unlabeled Issues
on:
  issues:
    types: [opened]

jobs:
  close_unlabeled_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Check if issue has labels
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        LABELS=$(curl -s -H "Authorization: token $GH_TOKEN" \
        "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" \
        | jq '.labels | length')

        if [[ $LABELS -eq 0 ]]; then
          curl -s -X PATCH -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" \
          -d '{"state":"closed"}'
          echo "Issue #${{ github.event.issue.number }} has been closed due to missing labels."
        else
          echo "Issue #${{ github.event.issue.number }} has labels, no action taken."
        fi
