name: Auto-close issues without labels

on:
  issues:
    types: [opened, edited]

jobs:
  auto_close_unlabeled_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue if it has no labels
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;

            if (issue.labels.length === 0) {
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `@${issue.user.login} 你好！由于此 issue 没有任何标签，将被自动关闭。请确保按照模板提交并添加相应标签。谢谢！`
              });

              await github.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed'
              });
            }
